package com.java.ExceptionHandling;
import java.io.*;  
public class M {
	 
		 void method()throws IOException{  
		  System.out.println("device operation performed");  
		 }  
		 
		 /*
		  * 
		  * 
		  * 
		  * import java.io.*;  
class M{  
 void method()throws IOException{  
  throw new IOException("device error");  
 }  
}  
class Testthrows4{  
   public static void main(String args[])throws IOException{//declare exception  
     M m=new M();  
     m.method();  
  
    System.out.println("normal flow...");  
  }  
}  
		  * 
		  * In case we declare the exception and the exception occurs, 
		  * it will be thrown at runtime because throws does not handle the exception.
		  * 
		  * 
		  * 
		  * 
		  * 
		  */
		}  

